// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAiMsPhP-xR344ea8-zrfQvVl-hRmOC4',
    appId: '1:456402748036:web:22c33a6de33eb1b28178d1',
    messagingSenderId: '456402748036',
    projectId: 'flutter-project-d2657',
    authDomain: 'flutter-project-d2657.firebaseapp.com',
    storageBucket: 'flutter-project-d2657.appspot.com',
    measurementId: 'G-W0F9Q5WV3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbCYUT-2yU4s7Znrgoq3wEtmYoD3u57E',
    appId: '1:456402748036:android:6eb9ee7c4a1a6bf78178d1',
    messagingSenderId: '456402748036',
    projectId: 'flutter-project-d2657',
    storageBucket: 'flutter-project-d2657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVqr3Loy6kEx9DSRIwPUnu7322ytVzuPo',
    appId: '1:456402748036:ios:05c32c088cdb807b8178d1',
    messagingSenderId: '456402748036',
    projectId: 'flutter-project-d2657',
    storageBucket: 'flutter-project-d2657.appspot.com',
    iosClientId: '456402748036-e4s4br6vmvhpd1q04gt5pl1sb7ff9636.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
